'use strict'

const ProdutoUnidadeController = require("../app/Controllers/Http/ProdutoUnidadeController")

const Route = use("Route")

Route.post('/users', 'UserController.create')
Route.get('/users', 'UserController.index')
Route.post('/sessions', 'SessionController.create')
Route.post('/imageUpload','ImageController.create')
Route.get('/produto_unidade/equal/:id', 'ProdutoUnidadeController.showProdutoUnidadeEqual')
Route.put('/produto_unidade/updateLocal/:id', 'ProdutoUnidadeController.updateLocal')
Route.resource('temperatura', 'TemperaturaController')
  .apiOnly()
  .middleware('auth')
Route.resource('sensor', 'SensorController')
  .apiOnly()
  .middleware('auth')
Route.resource('estoque', 'EstoqueController')
  .apiOnly()
  .middleware('auth')
Route.resource('produto', 'ProdutoController')
  .apiOnly()
  .middleware('auth')
Route.resource('produto_unidade', 'ProdutoUnidadeController')
  .apiOnly()
  .middleware('auth')
Route.resource('status_produto', 'StatusProdutoController')
  .apiOnly()
  .middleware('auth')
Route.resource('produto_meta','ProdutoMetaController')
  .apiOnly()
  .middleware('auth')